//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order_has_pckgd
    {
        public int fk_order_id { get; set; }
        public int fk_pckgd_id { get; set; }
        public int order_has_pckgd_id { get; set; }
        public int order_has_pckgd_amount { get; set; }
    
        public virtual tbl_order tbl_order { get; set; }
        public virtual tbl_packaged tbl_packaged { get; set; }
    }
}
