//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_order()
        {
            this.tbl_order_has_meal = new HashSet<tbl_order_has_meal>();
            this.tbl_order_has_pckgd = new HashSet<tbl_order_has_pckgd>();
        }
    
        public int order_id { get; set; }
        public string order_status { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<double> order_totalPrice { get; set; }
        public int fk_check_id { get; set; }
    
        public virtual tbl_check tbl_check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_has_meal> tbl_order_has_meal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_has_pckgd> tbl_order_has_pckgd { get; set; }
    }
}
